import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-d1-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`pages_blocks_hero\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_services\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_about\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_core_values\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_vision_mission_items\` ADD \`icon\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_vision_mission\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_contact_persons\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_complaints\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_social\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_vacancies\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_accordion\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_hero\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_services\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_about\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_core_values\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_vision_mission_items\` ADD \`icon\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_vision_mission\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_contact_persons\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_complaints\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_social\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_vacancies\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_accordion\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`pages\` DROP COLUMN \`content\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` DROP COLUMN \`version_content\`;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`pages\` ADD \`content\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` ADD \`version_content\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_hero\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_services\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_about\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_core_values\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_vision_mission_items\` DROP COLUMN \`icon\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_vision_mission\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_contact_persons\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_complaints\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_social\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_vacancies\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_accordion\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_hero\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_services\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_about\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_core_values\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_vision_mission_items\` DROP COLUMN \`icon\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_vision_mission\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_contact_persons\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_complaints\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_social\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_vacancies\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_accordion\` DROP COLUMN \`header_icon\`;`)
}
