import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-d1-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`pages_blocks_hero\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_hero\` DROP COLUMN \`header_eyebrow\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_hero\` DROP COLUMN \`cert_link_variant\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_services_cards\` DROP COLUMN \`link_variant\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_services\` DROP COLUMN \`header_subtitle\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_services\` DROP COLUMN \`header_intro\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_about\` DROP COLUMN \`header_subtitle\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_about\` DROP COLUMN \`header_intro\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_core_values\` DROP COLUMN \`header_subtitle\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_core_values\` DROP COLUMN \`header_intro\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_vision_mission\` DROP COLUMN \`header_subtitle\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_vision_mission\` DROP COLUMN \`header_intro\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_contact_persons\` DROP COLUMN \`header_intro\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_complaints\` DROP COLUMN \`header_subtitle\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_social\` DROP COLUMN \`header_intro\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_social\` DROP COLUMN \`link_variant\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_vacancies_cards\` DROP COLUMN \`link_variant\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_vacancies\` DROP COLUMN \`header_subtitle\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_accordion\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_hero\` DROP COLUMN \`header_icon\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_hero\` DROP COLUMN \`header_eyebrow\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_hero\` DROP COLUMN \`cert_link_variant\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_services_cards\` DROP COLUMN \`link_variant\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_services\` DROP COLUMN \`header_subtitle\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_services\` DROP COLUMN \`header_intro\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_about\` DROP COLUMN \`header_subtitle\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_about\` DROP COLUMN \`header_intro\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_core_values\` DROP COLUMN \`header_subtitle\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_core_values\` DROP COLUMN \`header_intro\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_vision_mission\` DROP COLUMN \`header_subtitle\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_vision_mission\` DROP COLUMN \`header_intro\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_contact_persons\` DROP COLUMN \`header_intro\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_complaints\` DROP COLUMN \`header_subtitle\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_social\` DROP COLUMN \`header_intro\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_social\` DROP COLUMN \`link_variant\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_vacancies_cards\` DROP COLUMN \`link_variant\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_vacancies\` DROP COLUMN \`header_subtitle\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_accordion\` DROP COLUMN \`header_icon\`;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`pages_blocks_hero\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_hero\` ADD \`header_eyebrow\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_hero\` ADD \`cert_link_variant\` text DEFAULT 'primary';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_services_cards\` ADD \`link_variant\` text DEFAULT 'primary';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_services\` ADD \`header_subtitle\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_services\` ADD \`header_intro\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_about\` ADD \`header_subtitle\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_about\` ADD \`header_intro\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_core_values\` ADD \`header_subtitle\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_core_values\` ADD \`header_intro\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_vision_mission\` ADD \`header_subtitle\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_vision_mission\` ADD \`header_intro\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_contact_persons\` ADD \`header_intro\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_complaints\` ADD \`header_subtitle\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_social\` ADD \`header_intro\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_social\` ADD \`link_variant\` text DEFAULT 'primary';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_vacancies_cards\` ADD \`link_variant\` text DEFAULT 'primary';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_vacancies\` ADD \`header_subtitle\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_accordion\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_hero\` ADD \`header_icon\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_hero\` ADD \`header_eyebrow\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_hero\` ADD \`cert_link_variant\` text DEFAULT 'primary';`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_services_cards\` ADD \`link_variant\` text DEFAULT 'primary';`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_services\` ADD \`header_subtitle\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_services\` ADD \`header_intro\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_about\` ADD \`header_subtitle\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_about\` ADD \`header_intro\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_core_values\` ADD \`header_subtitle\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_core_values\` ADD \`header_intro\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_vision_mission\` ADD \`header_subtitle\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_vision_mission\` ADD \`header_intro\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_contact_persons\` ADD \`header_intro\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_complaints\` ADD \`header_subtitle\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_social\` ADD \`header_intro\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_social\` ADD \`link_variant\` text DEFAULT 'primary';`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_vacancies_cards\` ADD \`link_variant\` text DEFAULT 'primary';`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_vacancies\` ADD \`header_subtitle\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_accordion\` ADD \`header_icon\` text;`)
}
