/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    comments: Comment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Authors edit & submit for review. Reviewers approve (Ready) and publish.
   */
  roles: ('admin' | 'reviewer' | 'author')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Advanced with the action button (Submit for review → Approve → Publish).
   */
  workflowStatus: 'draft' | 'review' | 'ready';
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Page sections rendered on the site, in order.
   */
  layout?:
    | (
        | HeroBlock
        | ServicesBlock
        | AboutBlock
        | CoreValuesBlock
        | VisionMissionBlock
        | ContactPersonsBlock
        | ComplaintsBlock
        | SocialBlock
        | VacanciesBlock
        | AccordionBlock
        | ButtonRowBlock
        | RichTextBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  header?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    intro?: string | null;
  };
  buttons?:
    | {
        label: string;
        variant?: ('primary' | 'secondary') | null;
        type?: ('internal' | 'external') | null;
        page?: (number | null) | Page;
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  cert: {
    title?: string | null;
    text?: string | null;
    link: {
      label: string;
      variant?: ('primary' | 'secondary') | null;
      type?: ('internal' | 'external') | null;
      page?: (number | null) | Page;
      url?: string | null;
      newTab?: boolean | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock".
 */
export interface ServicesBlock {
  header?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    intro?: string | null;
  };
  tabs?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  cards?:
    | {
        number?: string | null;
        title?: string | null;
        description?: string | null;
        link: {
          label: string;
          variant?: ('primary' | 'secondary') | null;
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'services';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock".
 */
export interface AboutBlock {
  header?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    intro?: string | null;
  };
  body?: string | null;
  email?: string | null;
  buttons?:
    | {
        label: string;
        variant?: ('primary' | 'secondary') | null;
        type?: ('internal' | 'external') | null;
        page?: (number | null) | Page;
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoreValuesBlock".
 */
export interface CoreValuesBlock {
  header?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    intro?: string | null;
  };
  values?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'coreValues';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VisionMissionBlock".
 */
export interface VisionMissionBlock {
  header?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    intro?: string | null;
  };
  items?:
    | {
        heading?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'visionMission';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactPersonsBlock".
 */
export interface ContactPersonsBlock {
  header?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    intro?: string | null;
  };
  people?:
    | {
        name?: string | null;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactPersons';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComplaintsBlock".
 */
export interface ComplaintsBlock {
  header?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    intro?: string | null;
  };
  steps?:
    | {
        title?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'complaints';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialBlock".
 */
export interface SocialBlock {
  header?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    intro?: string | null;
  };
  handle?: string | null;
  link: {
    label: string;
    variant?: ('primary' | 'secondary') | null;
    type?: ('internal' | 'external') | null;
    page?: (number | null) | Page;
    url?: string | null;
    newTab?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'social';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VacanciesBlock".
 */
export interface VacanciesBlock {
  header?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    intro?: string | null;
  };
  cards?:
    | {
        title?: string | null;
        location?: string | null;
        hours?: string | null;
        text?: string | null;
        link: {
          label: string;
          variant?: ('primary' | 'secondary') | null;
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'vacancies';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock".
 */
export interface AccordionBlock {
  header?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    intro?: string | null;
  };
  items?:
    | {
        title: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonRowBlock".
 */
export interface ButtonRowBlock {
  buttons?:
    | {
        label: string;
        variant?: ('primary' | 'secondary') | null;
        type?: ('internal' | 'external') | null;
        page?: (number | null) | Page;
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  alignment?: ('left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'buttonRow';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  width?: ('narrow' | 'wide') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  page: number | Page;
  /**
   * The page version this comment was made against.
   */
  versionId?: string | null;
  /**
   * Optional dot-path of the field the comment targets (for inline comments).
   */
  fieldPath?: string | null;
  body: string;
  author?: (number | null) | User;
  resolved?: boolean | null;
  /**
   * Set to reply within a thread.
   */
  parent?: (number | null) | Comment;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  workflowStatus?: T;
  content?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        services?: T | ServicesBlockSelect<T>;
        about?: T | AboutBlockSelect<T>;
        coreValues?: T | CoreValuesBlockSelect<T>;
        visionMission?: T | VisionMissionBlockSelect<T>;
        contactPersons?: T | ContactPersonsBlockSelect<T>;
        complaints?: T | ComplaintsBlockSelect<T>;
        social?: T | SocialBlockSelect<T>;
        vacancies?: T | VacanciesBlockSelect<T>;
        accordion?: T | AccordionBlockSelect<T>;
        buttonRow?: T | ButtonRowBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        intro?: T;
      };
  buttons?:
    | T
    | {
        label?: T;
        variant?: T;
        type?: T;
        page?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  cert?:
    | T
    | {
        title?: T;
        text?: T;
        link?:
          | T
          | {
              label?: T;
              variant?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock_select".
 */
export interface ServicesBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        intro?: T;
      };
  tabs?:
    | T
    | {
        label?: T;
        id?: T;
      };
  cards?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        link?:
          | T
          | {
              label?: T;
              variant?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock_select".
 */
export interface AboutBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        intro?: T;
      };
  body?: T;
  email?: T;
  buttons?:
    | T
    | {
        label?: T;
        variant?: T;
        type?: T;
        page?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoreValuesBlock_select".
 */
export interface CoreValuesBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        intro?: T;
      };
  values?:
    | T
    | {
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VisionMissionBlock_select".
 */
export interface VisionMissionBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        intro?: T;
      };
  items?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactPersonsBlock_select".
 */
export interface ContactPersonsBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        intro?: T;
      };
  people?:
    | T
    | {
        name?: T;
        role?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComplaintsBlock_select".
 */
export interface ComplaintsBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        intro?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialBlock_select".
 */
export interface SocialBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        intro?: T;
      };
  handle?: T;
  link?:
    | T
    | {
        label?: T;
        variant?: T;
        type?: T;
        page?: T;
        url?: T;
        newTab?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VacanciesBlock_select".
 */
export interface VacanciesBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        intro?: T;
      };
  cards?:
    | T
    | {
        title?: T;
        location?: T;
        hours?: T;
        text?: T;
        link?:
          | T
          | {
              label?: T;
              variant?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock_select".
 */
export interface AccordionBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        intro?: T;
      };
  items?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonRowBlock_select".
 */
export interface ButtonRowBlockSelect<T extends boolean = true> {
  buttons?:
    | T
    | {
        label?: T;
        variant?: T;
        type?: T;
        page?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  alignment?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  width?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  page?: T;
  versionId?: T;
  fieldPath?: T;
  body?: T;
  author?: T;
  resolved?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * The navigation links shown in the header, in order.
   */
  navItems?:
    | {
        label: string;
        type?: ('internal' | 'external') | null;
        page?: (number | null) | Page;
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The button on the right side of the header (teal pill). Leave the label empty to hide it.
   */
  cta?: {
    label?: string | null;
    type?: ('internal' | 'external') | null;
    page?: (number | null) | Page;
    url?: string | null;
    newTab?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  menuItems?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  infoLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        newTab?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  email?: T;
  phone?: T;
  address?: T;
  menuItems?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  infoLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}