/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    comments: Comment;
    aanmeldingen: Aanmeldingen;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    aanmeldingen: AanmeldingenSelect<false> | AanmeldingenSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'aanmelding-instellingen': AanmeldingInstellingen;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'aanmelding-instellingen': AanmeldingInstellingenSelect<false> | AanmeldingInstellingenSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Authors edit & submit for review. Reviewers approve (Ready) and publish.
   */
  roles: ('admin' | 'reviewer' | 'author')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short description of the image for screen readers and when the image can’t load. Important for accessibility and SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Advanced with the action button (Submit for review → Approve → Publish).
   */
  workflowStatus: 'draft' | 'review' | 'ready';
  /**
   * Page sections rendered on the site, in order.
   */
  layout?:
    | (
        | HeroBlock
        | ServicesBlock
        | AboutBlock
        | CoreValuesBlock
        | VisionMissionBlock
        | ContactPersonsBlock
        | ComplaintsBlock
        | SocialBlock
        | VacanciesBlock
        | AccordionBlock
        | ButtonRowBlock
        | RichTextBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * When on, search engines are asked not to index or follow this page.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  header?: {
    title?: string | null;
    subtitle?: string | null;
    /**
     * Introductory paragraph shown below the title.
     */
    intro?: string | null;
  };
  /**
   * Large image that fills the right-hand side of the hero.
   */
  image?: (number | null) | Media;
  buttons?:
    | {
        /**
         * The text shown on the button.
         */
        label: string;
        /**
         * Visual style of the button.
         */
        variant?: ('primary' | 'secondary') | null;
        /**
         * Link to a page on this site (follows the page if its address changes) or to an external web address.
         */
        type?: ('internal' | 'external') | null;
        page?: (number | null) | Page;
        /**
         * Full web address, including https://
         */
        url?: string | null;
        /**
         * Optional. Scroll to a section on the selected page. Give the target section an Anchor ID for a readable link.
         */
        anchor?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock".
 */
export interface ServicesBlock {
  header?: {
    /**
     * Icon shown in the small label above the title. Leave empty for the default icon.
     */
    icon?: string | null;
    /**
     * Small line of text shown above the title.
     */
    eyebrow?: string | null;
    title?: string | null;
  };
  /**
   * Each tab shows its own set of service cards on the site.
   */
  tabs?:
    | {
        label?: string | null;
        cards?:
          | {
              /**
               * Icon shown in the white circle on the card. Leave empty for the default icon.
               */
              icon?: string | null;
              /**
               * Small number shown on the card (e.g. 01).
               */
              number?: string | null;
              title?: string | null;
              description?: string | null;
              link: {
                /**
                 * The text shown on the link.
                 */
                label: string;
                /**
                 * Link to a page on this site (follows the page if its address changes) or to an external web address.
                 */
                type?: ('internal' | 'external') | null;
                page?: (number | null) | Page;
                /**
                 * Full web address, including https://
                 */
                url?: string | null;
                /**
                 * Optional. Scroll to a section on the selected page. Give the target section an Anchor ID for a readable link.
                 */
                anchor?: string | null;
                newTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'services';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock".
 */
export interface AboutBlock {
  header?: {
    /**
     * Icon shown in the small label above the title. Leave empty for the default icon.
     */
    icon?: string | null;
    /**
     * Small line of text shown above the title.
     */
    eyebrow?: string | null;
    title?: string | null;
  };
  /**
   * Photo shown next to the text.
   */
  image?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Email address shown as a contact link in this section.
   */
  email?: string | null;
  buttons?:
    | {
        /**
         * The text shown on the button.
         */
        label: string;
        /**
         * Visual style of the button.
         */
        variant?: ('primary' | 'secondary') | null;
        /**
         * Link to a page on this site (follows the page if its address changes) or to an external web address.
         */
        type?: ('internal' | 'external') | null;
        page?: (number | null) | Page;
        /**
         * Full web address, including https://
         */
        url?: string | null;
        /**
         * Optional. Scroll to a section on the selected page. Give the target section an Anchor ID for a readable link.
         */
        anchor?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoreValuesBlock".
 */
export interface CoreValuesBlock {
  header?: {
    /**
     * Icon shown in the small label above the title. Leave empty for the default icon.
     */
    icon?: string | null;
    /**
     * Small line of text shown above the title.
     */
    eyebrow?: string | null;
    title?: string | null;
  };
  /**
   * Logo shown in the center of the circle of values.
   */
  logo?: (number | null) | Media;
  values?:
    | {
        label?: string | null;
        /**
         * Shown when the card is hovered.
         */
        description?: string | null;
        /**
         * Line-art icon shown in the value’s circle.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'coreValues';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VisionMissionBlock".
 */
export interface VisionMissionBlock {
  header?: {
    /**
     * Icon shown in the small label above the title. Leave empty for the default icon.
     */
    icon?: string | null;
    /**
     * Small line of text shown above the title.
     */
    eyebrow?: string | null;
    title?: string | null;
  };
  /**
   * Photo shown alongside the vision & mission items.
   */
  image?: (number | null) | Media;
  items?:
    | {
        /**
         * Icon shown in the round label. Leave empty for the default icon.
         */
        icon?: string | null;
        heading?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'visionMission';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactPersonsBlock".
 */
export interface ContactPersonsBlock {
  header?: {
    /**
     * Icon shown in the small label above the title. Leave empty for the default icon.
     */
    icon?: string | null;
    /**
     * Small line of text shown above the title.
     */
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
  };
  people?:
    | {
        name?: string | null;
        role?: string | null;
        /**
         * Portrait photo, aligned to the bottom of the card.
         */
        photo?: (number | null) | Media;
        phone?: string | null;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactPersons';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComplaintsBlock".
 */
export interface ComplaintsBlock {
  header?: {
    /**
     * Icon shown in the small label above the title. Leave empty for the default icon.
     */
    icon?: string | null;
    /**
     * Small line of text shown above the title.
     */
    eyebrow?: string | null;
    title?: string | null;
    /**
     * Introductory paragraph shown below the title.
     */
    intro?: string | null;
  };
  steps?:
    | {
        title?: string | null;
        text?: string | null;
        /**
         * Rounded callouts inside the step card (icon + text).
         */
        infoPills?:
          | {
              /**
               * Icon shown in the round badge. Leave empty for the default icon.
               */
              icon?: string | null;
              /**
               * Colour of the badge and text.
               */
              tone?: ('brand' | 'danger') | null;
              text?: string | null;
              /**
               * Optional arrow line shown below the callout text.
               */
              note?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional "Nog vragen?" card shown below the steps.
   */
  contact?: {
    /**
     * Leave empty to hide the card.
     */
    title?: string | null;
    subtitle?: string | null;
    /**
     * Portrait photo of the contact person.
     */
    photo?: (number | null) | Media;
    phone?: string | null;
    email?: string | null;
  };
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'complaints';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialBlock".
 */
export interface SocialBlock {
  header?: {
    /**
     * Icon shown in the small label above the title. Leave empty for the default icon.
     */
    icon?: string | null;
    /**
     * Small line of text shown above the title.
     */
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
  };
  /**
   * Social media username shown in the section (e.g. @burojazz).
   */
  handle?: string | null;
  link: {
    /**
     * The text shown on the link.
     */
    label: string;
    /**
     * Link to a page on this site (follows the page if its address changes) or to an external web address.
     */
    type?: ('internal' | 'external') | null;
    page?: (number | null) | Page;
    /**
     * Full web address, including https://
     */
    url?: string | null;
    /**
     * Optional. Scroll to a section on the selected page. Give the target section an Anchor ID for a readable link.
     */
    anchor?: string | null;
    newTab?: boolean | null;
  };
  /**
   * The photos in the collage, by position. Leave a slot empty to use the default photo.
   */
  photos?: {
    toys?: (number | null) | Media;
    gym?: (number | null) | Media;
    boxing?: (number | null) | Media;
    figures?: (number | null) | Media;
    phone?: (number | null) | Media;
    arrow?: (number | null) | Media;
    instagram?: (number | null) | Media;
  };
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'social';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VacanciesBlock".
 */
export interface VacanciesBlock {
  header?: {
    /**
     * Icon shown in the small label above the title. Leave empty for the default icon.
     */
    icon?: string | null;
    /**
     * Small line of text shown above the title.
     */
    eyebrow?: string | null;
    title?: string | null;
    /**
     * Introductory paragraph shown below the title.
     */
    intro?: string | null;
  };
  cards?:
    | {
        title?: string | null;
        location?: string | null;
        /**
         * Working hours for the vacancy (e.g. 32–36 hours per week).
         */
        hours?: string | null;
        text?: string | null;
        link: {
          /**
           * The text shown on the link.
           */
          label: string;
          /**
           * Link to a page on this site (follows the page if its address changes) or to an external web address.
           */
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          /**
           * Full web address, including https://
           */
          url?: string | null;
          /**
           * Optional. Scroll to a section on the selected page. Give the target section an Anchor ID for a readable link.
           */
          anchor?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'vacancies';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock".
 */
export interface AccordionBlock {
  header?: {
    /**
     * Small line of text shown above the title.
     */
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    /**
     * Introductory paragraph shown below the title.
     */
    intro?: string | null;
  };
  items?:
    | {
        title: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonRowBlock".
 */
export interface ButtonRowBlock {
  buttons?:
    | {
        /**
         * The text shown on the button.
         */
        label: string;
        /**
         * Visual style of the button.
         */
        variant?: ('primary' | 'secondary') | null;
        /**
         * Link to a page on this site (follows the page if its address changes) or to an external web address.
         */
        type?: ('internal' | 'external') | null;
        page?: (number | null) | Page;
        /**
         * Full web address, including https://
         */
        url?: string | null;
        /**
         * Optional. Scroll to a section on the selected page. Give the target section an Anchor ID for a readable link.
         */
        anchor?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  alignment?: ('left' | 'center' | 'right') | null;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'buttonRow';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  width?: ('narrow' | 'wide') | null;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  page: number | Page;
  /**
   * The page version this comment was made against.
   */
  versionId?: string | null;
  /**
   * Optional dot-path of the field the comment targets (for inline comments).
   */
  fieldPath?: string | null;
  body: string;
  author?: (number | null) | User;
  resolved?: boolean | null;
  /**
   * Set to reply within a thread.
   */
  parent?: (number | null) | Comment;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aanmeldingen".
 */
export interface Aanmeldingen {
  id: number;
  /**
   * Handling status of this submission. New submissions start as “Nieuw”; update it as the team picks it up.
   */
  status?: ('nieuw' | 'in-behandeling' | 'afgehandeld') | null;
  clientNaam: string;
  clientGeboortedatum: string;
  clientAdres: string;
  verwijzerNaam: string;
  verwijzerOrganisatie: string;
  verwijzerEmail: string;
  verwijzerTelefoon: string;
  moederNaam: string;
  moederAdres: string;
  moederEmail: string;
  moederTelefoon: string;
  vaderNaam: string;
  vaderAdres?: string | null;
  vaderEmail?: string | null;
  vaderTelefoon?: string | null;
  siblings?:
    | {
        leeftijd?: string | null;
        type?: ('broer' | 'zus' | 'nvt') | null;
        id?: string | null;
      }[]
    | null;
  redenAanmelden: string;
  hulpverleningsgeschiedenis?: string | null;
  problematiek?:
    | (
        | 'adhd'
        | 'ass'
        | 'verstandelijke-beperking'
        | 'hoogbegaafdheid'
        | 'emoties'
        | 'lichamelijke-klachten'
        | 'somberheid'
        | 'angst'
        | 'trauma'
        | 'drugsgebruik'
        | 'negatief-zelfbeeld'
        | 'vastlopen'
      )[]
    | null;
  problematiekOverig?: string | null;
  dsmDiagnoseBekend?: ('ja' | 'nee') | null;
  vormVanHulp?:
    ('begeleiding' | 'pmt' | 'basis-ggz' | 'ash' | 'wmo' | 'begeleiding-op-school' | 'diagnostiek')[] | null;
  privacyAkkoord: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'aanmeldingen';
        value: number | Aanmeldingen;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  workflowStatus?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        services?: T | ServicesBlockSelect<T>;
        about?: T | AboutBlockSelect<T>;
        coreValues?: T | CoreValuesBlockSelect<T>;
        visionMission?: T | VisionMissionBlockSelect<T>;
        contactPersons?: T | ContactPersonsBlockSelect<T>;
        complaints?: T | ComplaintsBlockSelect<T>;
        social?: T | SocialBlockSelect<T>;
        vacancies?: T | VacanciesBlockSelect<T>;
        accordion?: T | AccordionBlockSelect<T>;
        buttonRow?: T | ButtonRowBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        title?: T;
        subtitle?: T;
        intro?: T;
      };
  image?: T;
  buttons?:
    | T
    | {
        label?: T;
        variant?: T;
        type?: T;
        page?: T;
        url?: T;
        anchor?: T;
        newTab?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock_select".
 */
export interface ServicesBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        icon?: T;
        eyebrow?: T;
        title?: T;
      };
  tabs?:
    | T
    | {
        label?: T;
        cards?:
          | T
          | {
              icon?: T;
              number?: T;
              title?: T;
              description?: T;
              link?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock_select".
 */
export interface AboutBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        icon?: T;
        eyebrow?: T;
        title?: T;
      };
  image?: T;
  body?: T;
  email?: T;
  buttons?:
    | T
    | {
        label?: T;
        variant?: T;
        type?: T;
        page?: T;
        url?: T;
        anchor?: T;
        newTab?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoreValuesBlock_select".
 */
export interface CoreValuesBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        icon?: T;
        eyebrow?: T;
        title?: T;
      };
  logo?: T;
  values?:
    | T
    | {
        label?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VisionMissionBlock_select".
 */
export interface VisionMissionBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        icon?: T;
        eyebrow?: T;
        title?: T;
      };
  image?: T;
  items?:
    | T
    | {
        icon?: T;
        heading?: T;
        body?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactPersonsBlock_select".
 */
export interface ContactPersonsBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        icon?: T;
        eyebrow?: T;
        title?: T;
        subtitle?: T;
      };
  people?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        phone?: T;
        email?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComplaintsBlock_select".
 */
export interface ComplaintsBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        icon?: T;
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        infoPills?:
          | T
          | {
              icon?: T;
              tone?: T;
              text?: T;
              note?: T;
              id?: T;
            };
        id?: T;
      };
  contact?:
    | T
    | {
        title?: T;
        subtitle?: T;
        photo?: T;
        phone?: T;
        email?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialBlock_select".
 */
export interface SocialBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        icon?: T;
        eyebrow?: T;
        title?: T;
        subtitle?: T;
      };
  handle?: T;
  link?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        anchor?: T;
        newTab?: T;
      };
  photos?:
    | T
    | {
        toys?: T;
        gym?: T;
        boxing?: T;
        figures?: T;
        phone?: T;
        arrow?: T;
        instagram?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VacanciesBlock_select".
 */
export interface VacanciesBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        icon?: T;
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  cards?:
    | T
    | {
        title?: T;
        location?: T;
        hours?: T;
        text?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
            };
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock_select".
 */
export interface AccordionBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        intro?: T;
      };
  items?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonRowBlock_select".
 */
export interface ButtonRowBlockSelect<T extends boolean = true> {
  buttons?:
    | T
    | {
        label?: T;
        variant?: T;
        type?: T;
        page?: T;
        url?: T;
        anchor?: T;
        newTab?: T;
        id?: T;
      };
  alignment?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  width?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  page?: T;
  versionId?: T;
  fieldPath?: T;
  body?: T;
  author?: T;
  resolved?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aanmeldingen_select".
 */
export interface AanmeldingenSelect<T extends boolean = true> {
  status?: T;
  clientNaam?: T;
  clientGeboortedatum?: T;
  clientAdres?: T;
  verwijzerNaam?: T;
  verwijzerOrganisatie?: T;
  verwijzerEmail?: T;
  verwijzerTelefoon?: T;
  moederNaam?: T;
  moederAdres?: T;
  moederEmail?: T;
  moederTelefoon?: T;
  vaderNaam?: T;
  vaderAdres?: T;
  vaderEmail?: T;
  vaderTelefoon?: T;
  siblings?:
    | T
    | {
        leeftijd?: T;
        type?: T;
        id?: T;
      };
  redenAanmelden?: T;
  hulpverleningsgeschiedenis?: T;
  problematiek?: T;
  problematiekOverig?: T;
  dsmDiagnoseBekend?: T;
  vormVanHulp?: T;
  privacyAkkoord?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Logo shown at the top-left of the header.
   */
  logo?: (number | null) | Media;
  /**
   * The navigation links shown in the header, in order.
   */
  navItems?:
    | {
        /**
         * The text shown on the link.
         */
        label: string;
        /**
         * Link to a page on this site (follows the page if its address changes) or to an external web address.
         */
        type?: ('internal' | 'external') | null;
        page?: (number | null) | Page;
        /**
         * Full web address, including https://
         */
        url?: string | null;
        /**
         * Optional. Scroll to a section on the selected page. Give the target section an Anchor ID for a readable link.
         */
        anchor?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The button on the right side of the header (teal pill). Leave the label empty to hide it.
   */
  cta?: {
    /**
     * The text shown on the link.
     */
    label?: string | null;
    /**
     * Link to a page on this site (follows the page if its address changes) or to an external web address.
     */
    type?: ('internal' | 'external') | null;
    page?: (number | null) | Page;
    /**
     * Full web address, including https://
     */
    url?: string | null;
    /**
     * Optional. Scroll to a section on the selected page. Give the target section an Anchor ID for a readable link.
     */
    anchor?: string | null;
    newTab?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Logo shown in the footer.
   */
  logo?: (number | null) | Media;
  /**
   * Certification or quality-mark logo shown in the footer.
   */
  certImage?: (number | null) | Media;
  /**
   * Short line of text shown next to the footer logo.
   */
  tagline?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  /**
   * Main navigation links in the footer (first column).
   */
  menuItems?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Secondary links such as privacy statement and terms (second column).
   */
  infoLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aanmelding-instellingen".
 */
export interface AanmeldingInstellingen {
  id: number;
  /**
   * Optional personal message included in the confirmation email sent to the person who submitted the form. Leave empty to send only the standard acknowledgement. Do not put sensitive information here — it is emailed to the submitter.
   */
  bevestigingBericht?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        anchor?: T;
        newTab?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        anchor?: T;
        newTab?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  certImage?: T;
  tagline?: T;
  email?: T;
  phone?: T;
  address?: T;
  menuItems?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  infoLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aanmelding-instellingen_select".
 */
export interface AanmeldingInstellingenSelect<T extends boolean = true> {
  bevestigingBericht?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}